
GET http://localhost:8080/demo/all

###

POST http://localhost:8080/demo/add HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=Luis
&email=luis0921@gmail.com

###

PUT http://localhost:8080/demo/edit HTTP/1.1
Content-Type: application/x-www-form-urlencoded

id=105
&name=Usuario Editado 3
&email=editadonew@gmail.com

###

DELETE http://localhost:8080/demo/del HTTP/1.1
Content-Type: application/x-www-form-urlencoded

id=52

###

GET http://localhost:8080/demo/get/102

###

GET http://localhost:8080/demo/get/report

###
